### ISSUE TITLE
Crash for empty ClassNames

### ISSUE THREAD

**Issue by absolute-heike** [facebook/FBMemoryProfiler#11]
FBAllocationTrackerSummary instances with className being nil crash the Retain Cycle detection.

You could just filter nil entries in [FBMemoryProfilerDataSource _refilterSectionAtIndex:] but I guess we should find out, why a className can be nil in the first place.

This is a the Quickfix I implemented:
```
FBMemoryProfilerDataSource
- (NSArray *)_refilterSectionAtIndex:(NSInteger)index
{
  NSArray *filtered = [_data[index] filteredArrayUsingPredicate:
                       [NSPredicate predicateWithBlock:^BOOL(FBAllocationTrackerSummary *entry, NSDictionary *bindings) {
    NSString *className = entry.className.lowercaseString;
    if (_classFilter && [className rangeOfString:_classFilter].location == NSNotFound) {
      return NO;
    }

    if (entry.aliveObjects > 0 && entry.className) {
      return YES;
    }

    return NO;
  }]];
}
```

**Comment by Gricha** [comment]
Oh makes sense. I wonder why we get empty class in the first place. Were you able to find the class? We can take fix to this anyway, just in case, although it might be interesting to learn what's going on in there.

**Comment by absolute-heike** [comment]
Created a PR that fixes the bug. https://github.com/facebook/FBMemoryProfiler/pull/12

If I have time, I will debug further to find out, why it can be nil in the first place :)

**Comment by Gricha** [comment]
Awesome, thanks!

I'm gonna close it out right now, feel free to reopen if you discover something new in it.

**Comment by absolute-heike** [comment]
I found the reason for this!

The RestKit Library has a class RKMappingSourceObject, that forwards a whole bunch of methods to a property it owns. Amongst other things:
```
- (Class)class
{
    return [_object class];
}
```
If _object ist nil everything goes down. :)

I would suggest to add the fix in _isClassBlacklisted in FBAllocationTrackerImpl. Going to implement this fix today and create a PR for FBAllocationTracker if everything goes fine.

**Comment by absolute-heike** [comment]
PR created: https://github.com/facebook/FBAllocationTracker/pull/6 :)
