### ISSUE TITLE
FBAllocationTrackerSummary.className cause crash

### ISSUE THREAD

**Issue by HaloCXQ** [facebook/FBMemoryProfiler#13]
Though your define @property (nonatomic, copy, readonly, nonnull) NSString *className; It maybe nil. In FBMemoryProfilerDataSource the 241 line.[array addObject:object.className]  may add nil.

**Comment by absolute-heike** [comment]
Yeah, the fix to this was already merged in https://github.com/facebook/FBMemoryProfiler/issues/12

**Comment by HaloCXQ** [comment]
good.
