### ISSUE TITLE
Profiler Button Does not appear after adding profiler to the Project

### ISSUE THREAD

**Issue by ajaybeniwal** [facebook/FBMemoryProfiler#19]
I have added memory profile to the Objective-C project and initialised project but the Profile button is not appearing on the screen.

```
 [[FBAllocationTrackerManager sharedManager] startTrackingAllocations];
    [[FBAllocationTrackerManager sharedManager] enableGenerations];
  
    
    FBMemoryProfiler *memoryProfiler = [FBMemoryProfiler new];
    [memoryProfiler enable];
```

**Comment by Gricha** [comment]
Hey!

There is a confusion in README unfortunately. You need to retain memory profiler somewhere (keep it on your app delegate, or wherever you find it useful) right now after you enable it, it can get deallocated instantly.

I will update README to reflect that, in the mean time I'll keep the issue opened.

**Comment by Gricha** [comment]
Updated README to reflect that.

**Comment by ajaybeniwal** [comment]
Thanks it worked
