### ISSUE TITLE
How to port this to OSX? and it be used for swift?

### ISSUE THREAD

**Issue by steve21124** [facebook/FBMemoryProfiler#2]

**Comment by Gricha** [comment]
I actually never tried running this library with OSX app, I imagine you could try linking it in and checking if it's going to be working out of the box.

The framework will work in Swift apps (via bridging) and it will still be able to show Objective-C stuff. It doesn't support Swift right now.

If you have ideas how we could expand and evolve this project to support both OSX and Swift, we are always happy to see contributions! :)

Please reopen if you have more questions.
