### ISSUE TITLE
FBAllocationTrackerSummary nil className crash

### ISSUE THREAD

**Issue by ilsinszkibal** [facebook/FBMemoryProfiler#21]
Thanks a lot for taking the time to create this tool! ARC makes it easier to code, because it's still easy to create retain cycles or not create memory pressure because of missing autoreleasepool usage.

**About the crash:**
It can happen, that there are FBAllocationTrackerSummary instances with nil className. This will result in a crash in the FBMemoryProfilerDataSource's classNamesForSection: method.

Sometimes I can constantly reproduce it, sometimes it disappears. I've seen it both on device and simulator.

<img width="939" alt="screen shot 2016-04-29 at 4 42 28 pm" src="https://cloud.githubusercontent.com/assets/2144485/14920397/9880a92e-0e2d-11e6-912a-d71e7b977c48.png">

I've tried to look into this and the FBAllocationTrackerSummary do get created with an empty class name:

<img width="929" alt="screen shot 2016-04-29 at 5 06 04 pm" src="https://cloud.githubusercontent.com/assets/2144485/14920440/ec045834-0e2d-11e6-975c-484802ab3832.png">

Also a screenshot about the kv instance state in the FBAllocationTrackerManager.mm's _getSingleGenerationSummary, when the FBAllocationTrackerSummary is created.

![slice2](https://cloud.githubusercontent.com/assets/2144485/14920570/99c18ad2-0e2e-11e6-8c08-12549d66badd.png)

I hope that this is helpful :)

**Comment by Gricha** [comment]
Hey!

Thank you for reporting - this should already be fixed upstream, but the versions are not yet updated, I'll verify this and keep this open until then. Thank you so much!

**Comment by Gricha** [comment]
The versions have been bumped, I'm going to close out this issue, feel free to reopen if you are still experiencing it after an update.
