### ISSUE TITLE
why my app throw this error unsupported type encoding spec

### ISSUE THREAD

**Issue by xuzhengrong1** [facebook/FBMemoryProfiler#24]
NSGetSizeAndAlignment(): unsupported type encoding spec 'b' at 'b3' in 'b3'

**Comment by christyuj** [comment]
I also crash in this method NSGetSizeAndAlignment , the type encoding is 'b1' , i will find the reasons later

**Comment by kastiglione** [comment]
Thanks for the report. These errors happen when one of the ivars in an object holds a struct that uses bitfields (the `b` in these errors). There is work planned to prevent this crash from happening.

**Comment by Gricha** [comment]
This is actually an exception breakpoint. If you turn it off in Xcode it should not show up as crash, as well as it should not appear if you are not attached to lldb.

**Comment by xuzhengrong1** [comment]
I turn off the all exception breakpoint,it's ok. thx
