### ISSUE TITLE
pod install [!] Unable to find a specification for `FBMemoryProfiler`

### ISSUE THREAD

**Issue by chengxiaoyu00** [facebook/FBMemoryProfiler#25]
[!] Unable to find a specification for `FBMemoryProfiler`

**Comment by Gricha** [comment]
Can you please try again and specify in details how you achieved that effect? I am not able to reproduce.

Please make sure your `Podfile` is in the same place as xcode project you are working on.

If that does not help you and you still have an issue, feel free to reopen!

**Comment by chengxiaoyu00** [comment]
Well, I 've solved the problem , upgraded my CocoaPods

**Comment by RhettTamp** [comment]
can't I install this  repo if my cocoapods version is 1.4?
