### ISSUE TITLE
Crash EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by gshe** [facebook/FBMemoryProfiler#30]
FBMemoryProfile crash at FBWrapObjectGraphElement function

callstack:
![image](https://cloud.githubusercontent.com/assets/13896224/18079468/7b3abd22-6ec3-11e6-8d43-b925a639b8d4.png)

**Comment by kastiglione** [comment]
Sorry for the late answer. Are you able to reproduce this?

**Comment by BoxDengJZ** [comment]
I met too

**Comment by BoxDengJZ** [comment]
So common

**Comment by lafayea** [comment]
> Sorry for the late answer. Are you able to reproduce this?

everytime when I  press "Retain" button it crashes
