### ISSUE TITLE
can you dump memory?

### ISSUE THREAD

**Issue by canran** [facebook/FBMemoryProfiler#32]
hi,this day
i try to dump memory and relationship.when i see this tool,i think may be you can dump it ? 
like:hook malloc and free and scan the ptr?

**Comment by Gricha** [comment]
Memory Profiler doesn't currently allow you to just dump the memory easily. We're happy to see the pull request that adds support for it.

There might be other tools that would be more suit to support that as well, like chisel (cc @kastiglione )

**Comment by kastiglione** [comment]
@canran What do you want to do with the dumped memory? Xcode 8 has a memory debugger, and it can dump to .memgraph files. I don't know what the format of the file is, hence my question about what you want to do with the persisted memory graph. Other Apple tools can work on .memgraph files, but I don't if there's an API for that format.
