### ISSUE TITLE
AllocationTracker  dead lock

### ISSUE THREAD

**Issue by wangqianzhou** [facebook/FBMemoryProfiler#33]
![dead_lock_1](https://cloud.githubusercontent.com/assets/3773428/20003896/f6daa13e-a2c3-11e6-9618-c578ecae3911.png)
![dead_lock_2](https://cloud.githubusercontent.com/assets/3773428/20003904/fd39bbc8-a2c3-11e6-91b1-d7f57c0fdd0b.png)

**Comment by wangqianzhou** [comment]
The responsibility of the user

**Comment by JethroYe** [comment]
你好，我也遇到了这个问题，请问你是怎么修复呢？

**Comment by JethroYe** [comment]
> The responsibility of the user

你好，我也遇到了这个问题，请问你是怎么修复呢？
