### ISSUE TITLE
FBMemoryProfiler vs Apple Leak tool?

### ISSUE THREAD

**Issue by Nihility-Ming** [facebook/FBMemoryProfiler#6]
What is the difference and advantage of this open source project and Apple's own Leak tool?

**Comment by Gricha** [comment]
Hey, thanks for question.

I tried to outline this topic in the blogpost we released here:
https://code.facebook.com/posts/583946315094347/automatic-memory-leak-detection-on-ios

It all boils down to Retain Cycle Detector giving you ability to build automation around cycle detection. Apple's tools are very good at what they do, but they require manual intervention of developer building for profiling and actually doing profiling. With automation built around Retain Cycle Detector (possibly with use of AllocationTracker) we can skip some good chunk of manual work.

FBMemoryProfiler is an interface built on top of FBAllocationTracker and FBRetainCycleDetector. It does not necessarily offer automation part, but it's a showcase of how the tools can be used. It also can be built in all your builds and you can use it and play with it without even being near your Mac and/or attaching to Instruments.

Feel free to re-open this issue if you have more questions.
